### PR TITLE
Improvement/intrinsics

### PR DESCRIPTION
**Pull request by adrianherrera**
Support for intrinsics that commonly popped up in code that I attempted to instrument :)

Thoughts/comments welcome!

### CODE REVIEW

**Comment by sebastianpoeplau** [comment]
This is really nice @adrianherrera! I'm going to rebase the changes on the latest version of the code and try to merge them :blush:

**Comment by sebastianpoeplau** [comment]
Here's a summary of my changes, apart from resolving conflicts with new code:
- Drop the commit that officially enables LLVM 12 because we've done it on master already.
- From the commit introducing arithmetic with overflow detection, drop the parts that change how we represent Booleans in structures. We need the expressions to reflect the memory layout of the structs (see the comment on the struct case in `Symbolizer::createValueExpression`). However, I've added a commit that performs the necessary conversion in `extractvalue`/`insertvalue` (where floats were already handled similarly).
- Minor style changes for consistency.

**Comment by adrianherrera** [comment]
Great, thanks @sebastianpoeplau for the rebasing! Definitely would have been happy to do this, so appreciate the extra efforts

**Comment by sebastianpoeplau** [comment]
Thank you for the high-quality contribution! :wink:

**Pull request merged**
