### PR TITLE
Fixes #44 and #45, adds -Q, -W, -S option, afl++ support

### LINKED ISSUE #44: Failed to pipe the test input to afl-showmap
After building my own dockerfile and running on a target I constantly get:

```
[2021-01-24T11:35:15Z INFO  symcc_fuzzing_helper] Ignoring new test case /tmp/.tmpPBic7v/output/000011-optimistic because afl-showmap timed out on it
Error: Failed to check whether test case /tmp/.tmpPBic7v/output/000003-optimistic is interesting

Caused by:
    0: Failed to pipe the test input to afl-showmap
    1: Broken pipe (os error 32)
```
which results in terminating the exploration. and as it cant continue I have to wipe out/symcc, restart and it restarts from scratch ...

wouldn't it be better to just skip if this error comes up instead of terminating?

### PR DESCRIPTION
**Pull request by vanhauser-thc**
changes the error handling so that symcc_fuzzing_helper continues at all cost.
because without the ability to resume it is pretty pointless to run it otherwise.
It also adds the -Q option which forces afl-showmap qemu mode (so we can run symqemu although we fuzz an instrumented binary. for cases where symc++ fails for the target, and we do not want to waste an afl-fuzz-Q specifically for for symcc)

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
thanks to @domenukk for online rust support :)

**Comment by vanhauser-thc** [comment]
PR is done now and everything working for me :)

**Comment by sebastianpoeplau** [comment]
Very reasonable additions, and thanks for the implementation! I'll apply a few style changes and merge - give me a moment...

**Comment by vanhauser-thc** [comment]
change as much as you want - I am a rust novice, that was my second rust code ever ;)

**Comment by sebastianpoeplau** [comment]
Not bad :grin:

**Comment by sebastianpoeplau** [comment]
As I said in #49, I'm not sure why you would want to disable the coverage map when not in QEMU mode. Apart from that, sorry for the long delays - I'm really busy at the moment and trying to take care of SymCC and SymQEMU in my free time...

**Pull request closed without merging**
