### PR TITLE
Make symcc work with llvm 17

### PR DESCRIPTION
**Pull request by tokatoka**
llvm/Transforms/IPO/PassManagerBuilder.h doesn't exist on llvm 17

### CODE REVIEW

**Comment by aurelf** [comment]
Thanks for the PR, I added some CI tests for LLVM 16 and 17.
I think there is something else to be done for the QSym backend (on LLVM 17)...

**Comment by tokatoka** [comment]
I made the necessary change here
https://github.com/eurecom-s3/qsym/pull/1

**Comment by tokatoka** [comment]
i don't get why this breaks even for llvm 11, 12, 13, 14, 15 where i changed nothing.

**Comment by tokatoka** [comment]
I found out why
I need to add my change to symcc branch of eurecom-s3/qsym 

https://github.com/eurecom-s3/qsym/pull/3

then i'll update the submodule to symcc

**Comment by aurelf** [comment]
Indeed, that was the wrong branch, got confused too... Thanks !

**Comment by tokatoka** [comment]
sry i forgot to add ifdef
https://github.com/eurecom-s3/qsym/pull/4

**Comment by aurelf** [comment]
Excellent, thank you!

**Pull request merged**
